name: swipeable
description: >
  A widget that emits events when swiped past a threshold. Can be used to add
  quick actions for ListTiles.
version: 1.0.2
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/swipeable

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ^1.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
